apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcfm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bcfm-app
  template:
    metadata:
      labels:
        app: bcfm-app
    spec:
      containers:
      - name: bcfm-app
        image: 773182953673.dkr.ecr.eu-central-1.amazonaws.com/bcfmcase:latest
        ports:
        - containerPort: 8093
        readinessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: bcfm-app-service
spec:
  selector:
    app: bcfm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8093
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bcfm-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bcfm-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bcfm-app-service
            port:
              number: 80
